function dt_alert_dialog(title, message)

    d = dialog('Position',[600 800 300 150],'Name',title);
            
    txt = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[20 80 210 40],...
       'String',message);

    btn = uicontrol('Parent',d,...
       'Position',[85 20 70 25],...
       'String','OK',...
       'Callback','delete(gcf)');
               
    % make modal      
    uiwait(d);
    
end
